Api.Object.Title=Add Gitee API object for project
Input.Placeholder.Repo=Repo Name
Input.Placeholder.Owner=Owner
Generate=Generate
Select.Api.Objects=View Gitee API Owner/Repo options
Remove.Api.Object=Remove Owner/Repo
Remove.All.Api.Objects=Clear all Owner/Repo